# Numpy Tutorial
Numpy is python package. its stands for "Numercal python", its a library consisting of multidemenstional array objects and a collection of routuines processing of array

In [2]:
import numpy

In [3]:
a= numpy.array([1,2,3,4,5,6,7,8])


In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
b=numpy.array([44,45,46,77,88,99])

In [7]:
b

array([44, 45, 46, 77, 88, 99])

In [9]:
a.shape

(8,)

In [10]:
b.shape

(6,)

In [12]:
import numpy as np
c= np.array([1.2,4,4,4,4,8,7,7,])
c.shape

(8,)

In [14]:
#1D array creation 

a1=np.array([56,78,34,22])
a1

array([56, 78, 34, 22])

In [15]:
#2D Array creation
a= np.array([[1,2],[3,4]])
a


array([[1, 2],
       [3, 4]])

In [20]:
#3D array creation 
c=np.array([[1,2,3],[2,3,4],[3,4,5]])

c

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [21]:
d=np.array([[2,3,],[2,3],[2,7]])
d.shape

(3, 2)

In [33]:
x= np.array([[61,54,51],[32,78,12]])
x.shape
x.reshape(3,2)

array([[61, 54],
       [51, 32],
       [78, 12]])

In [38]:
g=np.array([[1,2,1],[1,4,7],[4,5,6]])
g

array([[1, 2, 1],
       [1, 4, 7],
       [4, 5, 6]])

In [42]:
h=np.array([[44,55],[44,88],[44,66]])
h.min()

44

In [43]:
h.max()

88

In [44]:
h.size

6

In [47]:
h.itemsize

4

In [48]:
h.dtype

dtype('int32')

In [49]:
h.data

In [50]:
a=np.array([[1,2],[4,5],[7,9]],dtype ='float64')

a

array([[1., 2.],
       [4., 5.],
       [7., 9.]])

In [51]:
a.dtype

dtype('float64')

In [52]:
a.itemsize

8

In [53]:
a.shape

(3, 2)

In [55]:
a.reshape(2,3)

array([[1., 2., 4.],
       [5., 7., 9.]])

In [57]:
x=np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [58]:
a =x.reshape(3,5)

In [59]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
a=x.reshape(5,3)

In [61]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
b=a.reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [66]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
a.ndim

2

In [69]:
b=np.array([[[4,5],[6,3]],[[5,7],[6,6]]])
b

array([[[4, 5],
        [6, 3]],

       [[5, 7],
        [6, 6]]])

In [70]:
b.ndim

3

In [71]:
type(a)

numpy.ndarray

In [72]:
ra = np.array([[1,2,3],[7,5,3]])
ra

array([[1, 2, 3],
       [7, 5, 3]])

In [73]:
#ravel operation where you can convert one numpy array into single row
print(ra.ravel())

[1 2 3 7 5 3]


In [74]:
b=np.array([[1.5,3,4],[4,6,3]])

In [75]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
j= np.ones((2,3,4))
j

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [80]:
j.shape

(2, 3, 4)

In [81]:
j.ndim

3

In [84]:
np.ones((2,3,4),dtype =np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [86]:
np.empty((5,5))

array([[1.06099790e-312, 6.79038653e-313, 2.41907520e-312,
        2.05833592e-312, 6.79038654e-313],
       [2.41907520e-312, 2.05833592e-312, 2.22809558e-312,
        2.33419537e-312, 2.05833592e-312],
       [6.79038653e-313, 2.37663529e-312, 2.05833592e-312,
        2.41907520e-312, 2.56761491e-312],
       [1.93101617e-312, 1.03977794e-312, 1.06099790e-312,
        9.33678148e-313, 1.08221785e-312],
       [1.10343781e-312, 1.97345609e-312, 2.12199579e-313,
        8.34443015e-308, 2.22507386e-307]])

In [88]:
n=np.array([[2,3,4,5],[5,6,6,4],[7,8,9,4]])
b=n.reshape(4,3)
b

array([[2, 3, 4],
       [5, 5, 6],
       [6, 4, 7],
       [8, 9, 4]])

In [90]:
m=np.arange(27)
m.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [92]:
m.min()

0

In [93]:
m.max()

26

In [94]:
m.ndim

1

In [97]:
e=np.arange(0,10,2)
e

array([0, 2, 4, 6, 8])

In [99]:
r=np.arange(0,30,5)
r

array([ 0,  5, 10, 15, 20, 25])

In [100]:
np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [107]:
a= np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [108]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [111]:
a =np.array([20,30,40,50])
b= np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [112]:
c= a-b
print(c)

[20 29 38 47]


In [117]:
b**2


array([0, 1, 4, 9], dtype=int32)

In [119]:
b=np.random.random((2,3))
b

array([[0.93901251, 0.88683606, 0.52041846],
       [0.68573213, 0.05015085, 0.55276787]])

In [120]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [122]:
d=b+c
d

array([[1.93901251, 1.88683606, 1.52041846],
       [1.68573213, 1.05015085, 1.55276787]])

In [134]:
B=np.arange(3)

In [136]:
B

array([0, 1, 2])

In [128]:
#universal functions

In [137]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [138]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [140]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

In [142]:
##indexing slicing and iterating 

In [145]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
a[2]

2

In [148]:
a[2:5]

array([2, 3, 4])

In [149]:
a[-1]

9

In [150]:
a[-2]

8

In [152]:
a[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [153]:
a[0:3]

array([0, 1, 2])

In [155]:
a[::-1] #reverse the array of elements 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [156]:
a[-4:-2]

array([6, 7])

In [160]:
b=np.array([12,30,20,48,10,5])
b

array([12, 30, 20, 48, 10,  5])

In [161]:
b[-5:-2]

array([30, 20, 48])

In [162]:
##basic slicing an estension of python

In [164]:
import numpy as np
d1 =np.arange(20)
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [167]:
d1[0:20:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [171]:
#an ndarray objects is prepared by arange() function 
#slice the object is defined with start ,stop, step, values 2, 20 and 2 respectively
s =slice(2,20,2)
s

slice(2, 20, 2)

In [173]:
print(d1[s])

[ 2  4  6  8 10 12 14 16 18]


In [174]:
d2 = np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [175]:
d2[5:] #slicing from 5th index till the end of the array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [176]:
d3 = np.array([np.nan,2,4,5,np.nan,6,7,8])
d3

array([nan,  2.,  4.,  5., nan,  6.,  7.,  8.])

In [177]:
#  ~ tilled symoble is not operator

In [178]:
print(d3[~np.isnan(d3)])

[2. 4. 5. 6. 7. 8.]


In [179]:
# The random module provides nice function to generate random numbers (and also stastical distrubtion) of any given shape rand number will generate my number between 0 and 1

In [180]:
np.random.rand(2,2) # uniform distribution --> similar like random

array([[0.42331643, 0.18451183],
       [0.81961122, 0.32102877]])

In [181]:
#Rand  will generate all positive numbers
#rand will generate any number for normal distribution in the given dimentions format


In [183]:
#randn fuction will generate the both positive and negaitve numbers
np.random.randn(2,3)

array([[-1.90620956,  0.82583565, -0.54955193],
       [-0.11941911,  0.01506055, -0.00760347]])