In [2]:
#creating numpy nd arraay object

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#using tuples to create an array
arr = np.array((1,2,3,4))
print(arr)
print (type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
#creating 0 D array with value 42
arr = np.array(42)
print(arr)


42


In [10]:
# 1 D array containing the value: 1,2,3,4,5,6
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
# 2 D array containg the value 1,2,3,4 and 6,3,4,5
import numpy as np 
arr = np.array([[1,2,3,4],[6,3,4,5]])
print(arr)


[[1 2 3 4]
 [6 3 4 5]]


In [14]:
# 3 D array containg value of 3,2,1 and 1,2,3 and 4,5,6
import numpy as np 
arr = np.array([[1,2,3],[3,2,1],[4,5,6]])
print(arr)


[[1 2 3]
 [3 2 1]
 [4 5 6]]


In [19]:
# To check the number of dimenstions

#check how many dimenstion the array have

a= np.array(42)
b= np.array([1,2,2,3])
c= np.array([[5,6,6],[4,6,8]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2
3


In [21]:
#Higher dimemsional array
# an array can have any number of dimensions 
import numpy as np
arr = np.array([1,2,5,3],ndmin =5)
print(arr)
print('number of dimentions:', arr.ndim)

[[[[[1 2 5 3]]]]]
number of dimentions: 5


In [22]:
#accessing array elements 
#array indexing is same as accessing the an array of elements 

#---> GET the first element from the array 
import numpy as np
arr = np.array([1,2,5,4])
print(arr[0])



1


In [23]:
#---> GET the second  element from the array 
import numpy as np
arr = np.array([1,2,5,4])
print(arr[1])

2


In [26]:
#---> GET the thrid and fourth element from the array and add them 
import numpy as np
arr = np.array([1,2,5,4])
print(arr[2], arr[3])
print(arr[2] + arr[3])


5 4
9


In [27]:
##### Acessing the 2 D arrays
#--->Access the 2nd element on 1st dimensions
import numpy as np
arr = np.array([[1,3,4,5],[5,6,7,8]])
print('2nd element first dimesion:', arr[0,1])

2nd element first dimesion 3


In [28]:
#--->Access the 3nd element on 2st dimensions
import numpy as np
arr = np.array([[1,3,4,5],[5,6,7,8]])
print('3nd element 2nd dimesion:', arr[1,2])

3nd element 2nd dimesion: 7


In [29]:
#Access the third element of second array of the first array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [30]:
#slicing arrays 

import numpy as np
arr = np.array([1,2,2,4,5,6,7,8])
print(arr[1:5])


[2 2 4 5]


In [32]:
#slice the elements from index 4 to the end of the array:

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3:])

[ 4  5  6  7  8  9 10]


In [36]:
#slice the elements from index 1 to the end of the array by step wise

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:9:2])


[3 5 7 9]


In [38]:
#Checking the Data Type of an Array
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

int32


In [ ]:
pip install mysql 

In [2]:
# write program to get numpy version and configuration 
import  numpy as np 
print(np.__version__)
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/adarshkumar/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/adarshkumar/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/adarshkumar/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\

In [3]:
#Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

import numpy as np
X = np.array([1,7,13,110])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array")
print("%d bytes" %(X.size * X.itemsize))

Original array:
[  1   7  13 110]
Size of the memory occupied by the said array
16 bytes


In [6]:
#Write a NumPy program to test whether none of the elements of a given array is zero

import numpy as np
x= np.array([1,2,3,4])
print("Original array")
print(x)
print("Test id none of the elements of the said array is zero:")
print(np.all(x))


Original array
[1 2 3 4]
Test id none of the elements of the said array is zero:
True


In [8]:
import numpy as np
x= np.array([0,2,3,4])
print("Original array")
print(x)
print("Test id none of the elements of the said array is zero:")
print(np.all(x))

Original array
[0 2 3 4]
Test id none of the elements of the said array is zero:
False


In [10]:
#Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

import numpy as np
a = np.array([1,0,np.nan,np.info])
print("original array")
print(a)
print("Test a given array element wise for finiteness:")
print(np.isfinite(a))

original array
[1 0 nan <function info at 0x000000CB0039B2F0>]
Test a given array element wise for finiteness:


TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [11]:
#Write a NumPy program to test element-wise for positive or negative infinity.

import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[ 1.  0. nan inf]
Test element-wise for positive or negative infinity:
[False False False  True]


In [12]:
#Write a NumPy program to test element-wise for NaN of a given array.
import numpy as np 
a = np.array([1,0, np.nan, np.inf])
print(a)
print("Test element wise for NAN")
print(np.isnan(a))

[ 1.  0. nan inf]
Test element wise for NAN
[False False  True False]


In [13]:
#Write a program to generate an array of 15 random numbers from a standard normal distribution.
import numpy as np
rand_num = np.random.normal(0,1,15)
print('15 random numbers from a standard  normal distribution ')
print(rand_num)

15 random numbers from a standard  normal distribution 
[-0.76964155  1.06884448 -0.38497338 -0.21800151  0.30859832  0.42059672
  2.59577441 -1.32690577  0.66793968  0.81819255  0.14412489  0.53951516
 -0.64547656 -0.46792711 -0.66127845]


In [14]:
#change data type from float to integer by using int
import numpy as np
arr= np.array([1.1,3.2,4.2])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 3 4]
int32


#The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [16]:
#Copy 
import numpy as np
arr = np.array([2,3,4,5,6,6])
x = arr.copy()
arr[0] = 53
print(arr)
print(x)


[53  3  4  5  6  6]
[2 3 4 5 6 6]


In [17]:
#view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]
